baseURL = "https://example.com"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "P.E. la"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [P.E. lab]() All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 2
[Languages.ja]
contentDir = "content/japanese"
copyright = "Copyright &copy; 2020 [P.E. lab]() All Rights Reserved"
home = "Home"
languageCode = "ja"
languageName = "Ja"
weight = 1
[[menu.footer]]
URL = "member"
name = "Member"
weight = 1
[[menu.footer]]
URL = "research"
name = "Research"
weight = 2
[[menu.footer]]
URL = "publications"
name = "Publications"
weight = 3
[[menu.footer]]
URL = "semminer"
name = "Semminer"
weight = 4

[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.main]]
URL = "member"
name = "Member"
weight = 1
[[menu.main]]
URL = "research"
name = "Research"
weight = 2
[[menu.main]]
URL = "publications"
name = "Publications"
weight = 3
[[menu.main]]
URL = "semminer"
name = "Semminer"
weight = 4
[[menu.main]]
URL = "research"
name = "Research"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5

[params]
author = "nohara"
contact_form_action = "#"
description = "This is meta description"
email = "nohara@pe.ska.life.tsukuba.ac.jp"
google_analitycs_id = ""
location = "1-1-1, Tenno-dai, Tsukuba, Ibaraki, Japan"
logo = "images/logo.png"
mobile = "0124857985320"
multi_author = false
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
